# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GraalVM Native Image builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  native-image-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Example step using Maven plugin  # https://graalvm.github.io/native-build-tools/latest/maven-plugin.html
        run: mvn -Pnative package -DskipTests
      - name: Remove JAR and original files
        run: |
          if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS" ]]; then
            # Linux and macOS
            find target/ -type f \( -name "*.jar" -or -name "*.original" \) -exec rm -f {} \;
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            # Windows PowerShell
            Remove-Item -Path target\*.jar -Force -ErrorAction SilentlyContinue
            Remove-Item -Path target\*.original -Force -ErrorAction SilentlyContinue
          fi
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: rhc-builder-${{ matrix.os }}
          path: target/rhc*
